/* member.js */

export const members = [
  { id: 1, name: "강효정", github: "ahyohyo", englishName: "KangHyojeong" },
  { id: 2, name: "김민아", github: "kimminna", englishName: "KimMina" },
  { id: 3, name: "김유민", github: "yumin-kim2", englishName: "KimYumin" },
  { id: 4, name: "김정민", github: "jjangminii", englishName: "KimJeongmin" },
  { id: 5, name: "김진아", github: "jinaaaaaaaaaaaaa", englishName: "KimJina" },
  { id: 6, name: "김충영", github: "chungyo", englishName: "KimChungyoung" },
  { id: 7, name: "노예원", github: "nyewon", englishName: "NohYewon" },
  { id: 8, name: "민경빈", github: "gyeongbibin", englishName: "MinGyeongBin" },
  { id: 9, name: "박소이", github: "soyyyyy", englishName: "ParkSoy" },
  { id: 10, name: "박우찬", github: "pwc2002", englishName: "ParkWoochan" },
  {
    id: 11,
    name: "박진석",
    github: "jin-evergreen",
    englishName: "ParkJinSeok",
  },
  { id: 12, name: "백지연", github: "jyeon03", englishName: "BaekJiyeon" },
  { id: 13, name: "송민서", github: "MinseoSONG", englishName: "SongMinseo" },
  {
    id: 14,
    name: "양승혜",
    github: "seunghye-rain",
    englishName: "YangSeunghye",
  },
  { id: 15, name: "오승택", github: "winchoose", englishName: "OhSeungtaek" },
  { id: 16, name: "이소희", github: "ssolsh", englishName: "Leesohee" },
  {
    id: 17,
    name: "이채영",
    github: "hummingbbird",
    englishName: "YiChaeyeong",
  },
  { id: 18, name: "이채원", github: "chaewon41", englishName: "LeeChaewon" },
  { id: 19, name: "이해니", github: "haeni82", englishName: "LeeHaenee" },
  { id: 20, name: "이현종", github: "Navi-Up", englishName: "LeeHyeonjong" },
  { id: 21, name: "이혜원", github: "ehye1", englishName: "LeeHyewon" },
  { id: 22, name: "장민수", github: "Tnalxmsk", englishName: "JangMinsu" },
  { id: 23, name: "정지원", github: "jiwonsudo", englishName: "JeongJiwon" },
  { id: 24, name: "최윤하", github: "twossu", englishName: "ChoiYoonha" },
  { id: 25, name: "한다경", github: "hdg0116", englishName: "HanDagyeong" },
  { id: 26, name: "황서진", github: "seojin15", englishName: "HwangSeojin" },
  { id: 27, name: "황유림", github: "yurimidaH", englishName: "HwangYurim" },
];
